### ISSUE TITLE
Why is the Fragment always wrap into Activity?

### ISSUE THREAD

**Issue by TonyTangAndroid** [jordifierro/android-base#4]
Hi there,  I am not absolutely sure why the `Fragment` is always wrapped into `Activity`. I understand that using `Fragment` is more flexible as a screen could have several fragments at the same time. For example, in a `Activity` with a`BottomNavigationBar`, it will definitely make sense to wrap different Fragments into the `Activity` holding `BottomNavigationBar` through `ViewPager`.

However, what I do not understand is that in this project all activities at most hold just one fragment. And we create extra `Listener` to communicate between `Fragment` and `Activity`, which is not necessary. 

Is it because we need to prepare for future use cases which will use several fragments in one activity or we wrap the fragment into activity at the very beginning to **keep consistency**?

Another question that I would like to ask is that, **must presenter only be referenced in Fragment**? Currently, in my project, I have a MainActivity, which uses BottomNavigationBar and ViewPager to hold three Fragments. And there are certain use cases that should be addressed this activity. 

For example, I need to check whether or not there is a newer version of App from server. If there is, our app will pop up a dialog to suggest users to download the apk and guide the uses to install it. I know the client update should be conducted in Google Play service. However, our potential customers might not be able to access Google Play service.  

I understand app upgrading logic has nothing to do with the fragments. It should be done in Activity. So what I intent to do is to inject a presenter in Activity. And in this presenter, it will address the logic of app upgrading. 

Is it good practice? Do you see a better one? Any suggestion will be appreciated.

**Comment by jordifierro** [comment]
Hi @TonyTangAndroid! I agree with all you have said.

The `Activity` per `Fragment` approach makes easier the implementation of a tablet version. You only need to replace the `Activities` (listeners are created with this purpose) and reuse the same fragments without need to change a single line of code. On the other hand, I think it's over-engineering and almost useless if you don't have planned to adapt the screens. This projects uses it because my goal was to learn and try some patterns, but I don't recommend it for a normal application. Try to keep it simple :)

I don't use a `Presenter` for `Activity` when it only contains pure graphical and navigation logic (in this project, for example), but it's absolutely normal (and a good practice) to use a `Presenter` for an `Activity`, or even for a `Service`, if they contain some kind of logic.

**Comment by TonyTangAndroid** [comment]
Thank you very much for getting me back. I also had confusion whether a `Presenter` should be applied in `Service` before you mentioning that it is also normal and good practice to use a `Presenter` in `Service`. Now almost all confusion has been cleared except **Presenter** part. 

Allow me to summarize my understanding about the use case, data repository and presenter.

The **use case** will address the business logic. It will address the most business logic in application.

The **data repository** will provide necessary data for the use case and provide proper way for use case to save data. 

And the **presenter** will serve as a bridge between use case and user interaction, which includes but not limited `Activity`, `Fragment` or `Service`. 


If I am understanding Presenter correctly, Presenter might get **complicated** if the presenter has several use case whose results will determine which following up use case should be executed. Would that be okay?

Please let me know if you a different understanding about use case, data and presenter, especially presenter part.

**Comment by jordifierro** [comment]
`Presenter` aims to be a pure Java implementation of the logic of an element tied to the framework (usually a screen). Thus, we can code a cleaner and more readable implementation of that element, and test it easily. I don't exactly like to see it as a bridge between use cases and user interaction but the element that handles the user interaction itself (and uses views and use cases to serve this purpose). Let me know if this makes sense to you.

I've been working with Presenters which use more than 10 use cases, some of them chained, and I think that `RxJava` reduces the complexity of this situation, making it easy to manage.

**Comment by TonyTangAndroid** [comment]
I see! And it makes more sense than I had defined. 

> I've been working with Presenters which use more than 10 use cases, some of them chained

To chain use case in presenter like RxJava way? Could you kindly please elaborate more about this? I did not manage to find a way to chain the use case in Presenter with RxJava. As when you a use case is executed, it expects a Subscriber and would not return an Observable. For me, the only way to chain another use case is to execute this use case in the callback method `onNext` of `Subcriber`. Are you also doing in this way? Or you have a better way? I had always thought that all chain logic could only be implemented in use case.

**Comment by jordifierro** [comment]
I usually chain the use cases on the `onNext` method of the `Subscriber`, as you say. 
In the case that two use cases have to be chained because it is part of the business logic of the application, that chaining must be done inside a use case itself.

For example, after a user register, the presenter calls the login use case, but maybe I want to wait for the user's confirmation by email, so they are two separate use cases and I chain them on the presenter. Other case is login and device registration to receive push notification. I always want to notify the notifications system when a user logs in the application, so both actions could be done on the same use case.

**Comment by TonyTangAndroid** [comment]
I see. The _`login and device registration`_ example has been well illuminate my understanding about use case. And I have been thinking about it. It makes sense. Thank you, Jordi.
