### ISSUE TITLE
Presenter Scope issue

### ISSUE THREAD

**Issue by TonyTangAndroid** [jordifierro/android-base#6]
In current repository, as all the Activity, Fragment & Presenter is matched one to one, so there won't be any issue. 

For my project, I have a activity which has a bottom navigation bar that holds three Fragment. And the first fragment holds several several ChildFragment. And each child fragment has a presenter. After Dagger is initialized, it seems that the children fragment is sharing the same presenter, which is not what I wanted.And the quick solution to resolve this issue is quite easy though, which is to remove the annotation  @ActivityScope in the presenter. 

I do understand the reason why it shares one presenter with annotation and why it create corresponding presenter without annotation.  But what I would like to know is that 

**How to create a new scope that will be matched per children fragment?**

I have created a pull request to demo what I am trying to achieve. 
Instead of showing a list of notes, it will show the note details in a view pager.

You could refer to this pull request https://github.com/jordifierro/android-base/pull/5 for more details. For now it will work as I removed the annotation in NoteDetailPresenterForViewPager.java

But if you added the annotation, it will not work as intended.

How to create a new scope that will be matched per children fragment? 

Thank you  very much for bearing me with such long verbose content.

**Comment by jordifierro** [comment]
Dagger scopes are used to determine whether an instance has to be created every time or reused for a concrete `Component`. You are the responsible of using correctly (create and store) this component for its own scope, for example: `@ActivityScope` notations is used on `ActivityComponent` providers and this `Component` must be created and reused inside each `Activity`. For each `Component` an instance can be `Singleton` or not.

That said, let's go to apply that in your case. You don't want to share the instances of the `Presenter` between child `Fragment` because that would lead to wrong behaviour. The easiest, and for me the best solution, is to remove the scope from the presenters, I see no point in making an scope if you don't need to share any instance. Is it right?

This project annotates the presenters with `@ActivityScope`, but that makes no difference with not doing it, apart from knowing where this element is being instantiated. Although, I think it's unnecessary if you want a new instance every time... so, as always, keep it simple :)

Tell me what you think about this!

**Comment by TonyTangAndroid** [comment]
I see. And I probably need more time to think about this as the project goes on. Thank you very much for your explanation and guidance.
