### ISSUE TITLE
use case dependency issue

### ISSUE THREAD

**Issue by TonyTangAndroid** [jordifierro/android-base#8]
Hello Jordi, I happened to run into a nice [talk](https://www.youtube.com/watch?v=3Mq5newPdck&t=1990s&index=13&list=WL) about Clean Architecture by Marko Milos. He mentioned that _use case_ could be called in _use case_. 

The following image is taken from his [slides](https://speakerdeck.com/markomilos/clean-architecture-on-android). Basically, an app have a use case like `GetLocationUseCase`. It will be used by several potential `presenter`. Then an app would also possibly have a use case like `GetRegionalTimelineUseCase`. Part of me thinks it makes sense that `GetRegionalTimelineUseCase` should call `GetLocationUseCase` directly without copying and paste the code in `GetLocationUseCase` again. But another part of me find it uncomfortable as I had thought it was not recommended to call use case in another use case. Use case should only be called by `Presenter`. Similarly, it is not a good practice for `repository` to call another `repository`. Otherwise, without these taboo,  it makes the architecture not so clean again. 

But again, it indeed feels so right that `GetRegionalTimelineUseCase` should call `GetLocationUseCase` directly. Could you please share me your thoughts on this issue?

<img width="965" alt="nested_use_case" src="https://cloud.githubusercontent.com/assets/8612724/24325850/6429a28a-1178-11e7-9a06-cce887c6b8ed.png">

**Comment by jordifierro** [comment]
In my opinion, it's absolutely correct to call a use case from another use case. Actually, I think it's a good practice in order to follow the don't repeat yourself principle and also respect the clean architecture layers.

There is no need for the presenter to call the `GetLocationUseCase` and then pass the date to the `GetRegionalTimelineUseCase` if view or user interaction is not required. The less business logic you put in the presenter, the better (and cleaner).

**Comment by TonyTangAndroid** [comment]
I see. Thank you very much for clarifying it. I get a feeling that everything is starting to connect together.
